# Generated by Django 4.2.25 on 2026-02-04 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0004_doctor_address_doctor_city_doctor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='notes',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage_instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medications',
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicines',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='prescription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
