# Generated by Django 4.2.25 on 2026-02-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0006_medicine_remove_prescription_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional biography', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='display_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
